project:
  type: website

website:
  title: "Graph Neural Networks"
  navbar:
    background: "#447099"
    align: center 
    collapse-below: lg
    left:
      - href: chapters/Introduction.qmd
        text: Introduction
      - href: chapters/Framework.qmd
        text: Framework
      - href: chapters/Empirical results.qmd
        text: Empirical results
      - href: chapters/Conclusion.qmd
        text: Conclusion
      - href: chapters/Slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true